### ISSUE TITLE
Add help button

### ISSUE THREAD

**Issue by PinkishCow** [BryceMatthes/betterdgg#23]
Have a link to this for force updating the extension http://i.imgur.com/Fc0hW4e.png and a link to chrome beta https://www.google.co.uk/chrome/browser/beta.html to fix a decent chunk of other issues. Also things like clear cache but make sure all boxes are checked and timeframe is set to beginning of time, refresh page, restart chrome, make a sacrifice to the devil, all that good stuff.

Edit out all the salt now i'm not mad anymore ¯\_(ツ)_/¯

**Comment by kenany** [comment]
Oh cool we have issues enabled now. Also I hope installing Chrome Beta doesn't actually fix anything; extension should work 100% on stable versions, otherwise we should fix that.

**Comment by PinkishCow** [comment]
Its not that it doesnt work, its that people blame unrelated issues on the extension

**Comment by PinkishCow** [comment]
such as the middle click scrolling

**Comment by PinkishCow** [comment]
Maybe the usernames of people who would be willing to help could be good too

**Comment by downthecrop** [comment]
Now that I am a certified jade master I think adding a help button in the footer of settings is a good choice ![help button](http://puu.sh/nVrP2/85719eb668.png). Do you think it's better to have it open a webpage in a new tab or another popup div like about?

**Comment by PinkishCow** [comment]
I feel that both have their good points, the jade popup would be more accessible and easy to access just to get things like usernames for people who could help but the wiki page can be more up to date and complete with help for various different issues

**Comment by downthecrop** [comment]
I think I've settled on having a wiki page. There shouldn't be too many problems past the jade popup for errors in the try catch. Just a little documentation, a redirect to post bugs and some info about the extension.

I can put this in pretty quick. I'll have it done soon.

**Comment by downthecrop** [comment]
Help button added in. Directs to the wiki page of this GitHub
