### ISSUE TITLE
settle on and enforce a single style

### ISSUE THREAD

**Issue by kenany** [BryceMatthes/betterdgg#28]
I would like for us to settle on a single coding style to follow and enforce it consistently across the codebase. Currently we are using a bit of everything. What style we do settle on is not important to me; what's important is that this style is consistently used everywhere. I know that this is a distraction from things like new features and setting up error handling but I believe this will make the code a bit easier to read/follow.

I am willingly to do all the work with regards to updating the entire codebase to the style and I'll even get [eslint](http://eslint.org/) set up so that we can check for style errors with a single command. Some things that we need to decide on:
- **indentation** Options are 2-space indent, 4-space indent, or the tab indent character itself. Also in some places things are just [completely misaligned](https://github.com/BryceMatthes/betterdgg/blob/429f9d1e1142c90ab71a5abea0552d2d63c02e9d/betterdgg/modules/chat.js#L27-L29). For the most part, the codebase is already using 4-space indent so I think we'll just stick with that.
- **semicolons** Optional in JavaScript. [This page](http://eslint.org/docs/rules/semi) and [this page](https://bonsaiden.github.io/JavaScript-Garden/#core.semicolon) describe some of the gotchas of automatic semicolon insertion. We can skip having them only if we are smart about it. For the most part we are currently using them everywhere but `passivestalk.js` currently has zero and `leftchat.js` is missing a few.
- **single or double quotes** We should just stick to using only one of these.
- **`==` vs `===`** Generally, [`===` is recommended](http://eslint.org/docs/rules/eqeqeq) because it won't surprise you with type coercion like:

``` js
0 == ''
// => true

0 === ''
// => false
```

These are smaller things like [brace-style](http://eslint.org/docs/rules/brace-style) and [space-before-function-paren](http://eslint.org/docs/rules/space-before-function-paren) but those will come later.

**Comment by downthecrop** [comment]
I like semicolons and moving to ===

4 space indentation is my preference

**Comment by kenany** [comment]
Mostly covered by https://github.com/BryceMatthes/betterdgg/pull/29.
