### ISSUE TITLE
Something is broken with the twitch chat button

### ISSUE THREAD

**Issue by PinkishCow** [BryceMatthes/betterdgg#40]
![Twitch chat button](http://puu.sh/o3V2r/c422a66ba2.png)

If the chat window reloads another button is added to the page, This occurs if you open the chat in another window, on your mobile or you click reload frame in the right click menu.

**Comment by downthecrop** [comment]
I got a fix for this, good find!

**Comment by downthecrop** [comment]
https://github.com/BryceMatthes/betterdgg/commit/d1d4f52940af992137e35ee329f135ae051cd0d4
