### ISSUE TITLE
xD text emote is broken

### ISSUE THREAD

**Issue by PinkishCow** [BryceMatthes/betterdgg#41]
xD text emote is broken

![xD](http://puu.sh/o5u6p/50e416b806.png)

If you select it the blank space also says xD

![xD](http://puu.sh/o5ugT/e154ee11d1.png)

I did notice it last version but completely forgot about it till i saw a random clear line in the chat caused by it

![xD](http://puu.sh/o5umT/c59de7a962.png)

**Comment by downthecrop** [comment]
Just need to add a line in https://github.com/BryceMatthes/betterdgg/blob/master/betterdgg/betterdgg.css with `display:none;` no big deal.

My mistake for not adding it when I put in xD as a text combo
