### ISSUE TITLE
BBD.GG contributor flair should be changed to the actual logo

### ISSUE THREAD

**Issue by canadianakin** [BryceMatthes/betterdgg#44]
The puzzle piece looks extremely out of place in the chat. In my opinion it should be replaced, the Aslan+ icon makes the most sense. This is the one I am referencing http://i.imgur.com/nC3Wy8i.png

**Comment by PinkishCow** [comment]
Thank you for being the only person so far to actually have an idea on what to change it to instead of just complaining like the other retards in chat :clap:

**Comment by downthecrop** [comment]
We've flipped the image horizontally and removed the plus. We'll see how this is received. The reason I moved from the old BBDGG contrib logo in the first place was for consistency. The puzzle piece image comes from the same theme/icon set as all other stock flairs.
