### ISSUE TITLE
/stalk is a bit wonky 

### ISSUE THREAD

**Issue by PinkishCow** [BryceMatthes/betterdgg#47]
I have not really got a clue how /stalk works but "johnnecro" was asking why it didn't update quickly, that being he got the same result for /stalk as he did 10 mins beforehand even though the other user had been speaking. Also refreshing does not work and some users are more upto date than others. 

Also if the user you used /stalk of speaks after the /stalk it treats it as a continuation of their message, not a clue if we could do anything about that but :+1: 
![wew lad](http://puu.sh/obmYS/2be53b2970.png)

**Comment by xDashh** [comment]
I'm also not quite sure how it's even working right now. As far as I'm aware the bdgg_service server handles those https://github.com/9inevolt/bdgg_service/blob/master/bdgg/handlers.py
which @BryceMatthes has running on one of which machines at the moment. I won't comment much how horrible that server is, I just want to say that, for now, we should probably remove all the code that interacts with that thing and just get the stalk info from the overrustleapi:

`http://overrustlelogs.net/api/v1/stalk/Destinygg%20chatlog/Dashh.json?limit=3` 
where the limit param can be anything reasonable, the server limits it at 200 iirc. The info about the most recent messages from chat is updated there within seconds.

**Comment by xDashh** [comment]
So #50 should fix the cacheing stuff completely, while I'm not sure how it could happen in the first place. Regarding:

> Also if the user you used /stalk of speaks after the /stalk it treats it as a continuation of their message, not a clue if we could do anything about that

Someone would have to test if this happens or rather why exactly. The stalk messages define their own type of ChatMessage, so I'm unsure how this is possible.

**Comment by xDashh** [comment]
So the issue that remains is shown here:
https://i.imgur.com/axW4f4M.png

Fixing that would probably require hooking into the function that handles displaying of chat messages, which @PurpleCox and me agreed is probably not worth it. It might be done in the future but is a very minor issue and as far as I am concerned this could be closed now.
