### ISSUE TITLE
Multiple highlight tiers, colors

### ISSUE THREAD

**Issue by Satou-gg** [BryceMatthes/betterdgg#52]
I'd like to have 2 different highlight colors. One for users that I've highlighted, and the other for actual messages where my username is mentioned. As it is, I'd like to highlight some users but sometimes I would like to ignore those highlights. This way with two different highlight colors, I could sometimes ignore highlighted users, while still keeping an eye out for mentions.

**Comment by PinkishCow** [comment]
Uhhh,  are you sure that you are using the bbdgg highlights not the default d.gg highlight adding?

**Comment by Satou-gg** [comment]
I'm not sure how to check which type I am using. They are all blue.

**Comment by PinkishCow** [comment]
Then you are not

**Comment by PinkishCow** [comment]
Ask downthecrop,  sgtmaximum or Sweetie_Belle how to do it because I am trying to go to sleep atm rip

**Comment by Satou-gg** [comment]
thx
