### ISSUE TITLE
Bot gets moved to Subscribers

### ISSUE THREAD

**Issue by kenany** [BryceMatthes/betterdgg#66]
Without bbdgg, Bot is correctly listed as a bot:

![chrome_2016-09-08_11-36-36](https://cloud.githubusercontent.com/assets/733364/18355895/acce2f62-75b8-11e6-9fd9-81ce00bb1f6e.png)

With bbdgg, Bot is moved to the subscribers list:

![chrome_2016-09-08_11-38-57](https://cloud.githubusercontent.com/assets/733364/18355946/deb350c0-75b8-11e6-9e1a-e2ffa3b936ed.png)

**Comment by downthecrop** [comment]
![image](https://cloud.githubusercontent.com/assets/4764745/18530797/609f21f0-7a90-11e6-8ce4-b7a3bbf55ec4.png)

I should have had the UserFeatures set for Bot's with the flair but I was setting it to ''.
