### ISSUE TITLE
Super halloween SpookerZ

### ISSUE THREAD

**Issue by PinkishCow** [BryceMatthes/betterdgg#68]
Have NOBULLY be normal for a second or so when posted and then flicker a bit and turn into the bully form for a day. 10/10 idea  ![](https://raw.githubusercontent.com/BryceMatthes/betterdgg/master/betterdgg/images/emoticons/NOBULLY.png)

**Comment by PinkishCow** [comment]
So i got it _working_ for now, i just used the preexisting spooky stuff and changed it a little. Also it doesn't recognise bbdgg emotes for no reason at all rip. its on my fork as a branch called highcolour

**Comment by xDashh** [comment]
Should work now with #69 . After that is merged, you can work on adding the NOBULLY effect which needs to be changed.
