### ISSUE TITLE
add emote pls

### ISSUE THREAD

**Issue by ILiedAboutCake** [BryceMatthes/betterdgg#85]
Add PepoThink kthx

https://cdn.discordapp.com/attachments/265256381437706240/278704513953562625/278301035305369601.png

**Comment by downthecrop** [comment]
I've made a deal with chat to add this and remove ShibeZ & HerbPerve. I'll do one more poll later.

**Comment by PinkishCow** [comment]
👌

**Comment by downthecrop** [comment]
Meme added 

https://github.com/BryceMatthes/betterdgg/commit/7acab27a3e82881d645c6a0f90dc2b6bbc99098e
